//! GEOF-01 acceptance proof: declared-geometry end-to-end round-trip (Phase 25, Plan 25-02).
//!
//! Proves that a declared `<scanSettings>` grid converts end-to-end with `pixel_count_source ==
//! "declared"` AND that declared geometry survives the forward→reverse→re-parse round-trip via the
//! `src/verify/geometry` symmetry assertion.
//!
//! ## Why a new test file instead of extending scan_settings.rs
//!
//! `tests/scan_settings.rs` documents its two-fixture split explicitly: `Synthetic_FullGeometry`
//! has declared geometry but NO `.ibd` (no convert path), while `Example_Processed` has an `.ibd`
//! but declares NO `<scanSettings>` grid. **Neither** fixture can serve as a declared-grid
//! convertible fixture. `Synthetic_DeclaredGrid` (generated by `gen_declared_geometry_fixture.py`,
//! Plan 25-02 Task 1) fills EXACTLY this gap: a 3×3 processed fixture WITH both a declared grid
//! AND a valid `.ibd`. This file exercises the FULL convert path over that fixture.
//!
//! ## Test flow
//!
//! 1. `parse_scan_settings` the fixture → assert the declared 3×3 grid surfaced.
//! 2. `ImagingReader::open` + `convert_with(.., Some(&geom), Some(&fixture))` to a temp `.mzpeak`.
//! 3. Re-open with `MzPeakReader` and assert `metadata.imaging.pixel_count_source == "declared"`,
//!    `pixel_count == {x:3,y:3}`, and a non-empty `scan_settings_list` carrying IMS:1000042/43.
//! 4. `reverse::convert` the produced archive to `out.imzML` + `out.ibd`.
//! 5. Call `assert_declared_geometry_symmetry(forward_geom, reverse_imzml)` and assert it passes.

use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use mzml2mzpeak::read::ImagingReader;
use mzml2mzpeak::reverse::convert as reverse_convert;
use mzml2mzpeak::schema::parse_scan_settings;
use mzml2mzpeak::verify::assert_declared_geometry_symmetry;
use mzml2mzpeak::write::{EncodingOptions, convert_with};

use mzpeak_prototyping::MzPeakReader;
use serde_json::Value;

/// The committed declared-grid fixture: 3×3 processed dataset WITH a paired `.ibd` AND a
/// declared `<scanSettingsList>` grid (IMS:1000042/43/44/45/46/47). The `.ibd` UUID/SHA-1 pair
/// passes the integrity preflight. Both the fixture IMZML and its IBD sidecar must be present.
const DECLARED_FIXTURE: &str = "tests/fixtures/imaging/Synthetic_DeclaredGrid.imzML";

/// The committed INCONSISTENT-grid fixture: declared grid 2×2 but observed pixel coords run to
/// 3×3 (observed extent exceeds the declared grid on both axes). The forward converter's GEOF-01
/// guard overwrites `pixel_count` with the observed maxima and records `observed_max`. Used by the
/// FIX-3 regression test. Generated by `gen_inconsistent_geometry_fixture.py`.
const INCONSISTENT_FIXTURE: &str = "tests/fixtures/imaging/Synthetic_InconsistentGrid.imzML";

/// Unique temp directory under the OS temp root for one test's outputs.
fn tempdir(tag: &str) -> PathBuf {
    static SEQ: AtomicU64 = AtomicU64::new(0);
    let n = SEQ.fetch_add(1, Ordering::Relaxed);
    let mut p = std::env::temp_dir();
    p.push(format!(
        "mzml2mzpeak_geom_rt_{tag}_{}_{n}",
        std::process::id()
    ));
    std::fs::create_dir_all(&p).expect("create temp work dir");
    p
}

/// GEOF-01 end-to-end: declared-geometry fixture converts to `pixel_count_source == "declared"`,
/// emits a `scan_settings_list` facet carrying IMS:1000042/43, reverses, and the
/// forward↔reverse declared-geometry symmetry assertion passes.
///
/// This test is the CI-fast proxy for PXD001283 declared-geometry acceptance. The PXD001283
/// gate (`tests/acceptance.rs`, `#[ignore]`) is UNCHANGED and still passes when run; this test
/// exercises the same declared-geometry code path on a tiny (9-spectrum, sub-second) fixture.
#[test]
fn declared_geometry_roundtrip() {
    // ---- PRECONDITION: fixture must exist (committed, no network) ----
    let fixture = Path::new(DECLARED_FIXTURE);
    assert!(
        fixture.exists(),
        "declared-grid fixture must be committed at {DECLARED_FIXTURE}"
    );

    // ---- STEP 1: parse declared geometry from the fixture imzML ----
    let geom = parse_scan_settings(fixture)
        .expect("parse_scan_settings on Synthetic_DeclaredGrid must succeed");

    // Assert the declared 3×3 grid is present (non-vacuous: proves the fixture declares it).
    assert_eq!(geom.grid_x, Some(3), "declared grid_x == 3");
    assert_eq!(geom.grid_y, Some(3), "declared grid_y == 3");
    assert_eq!(geom.pixel_size_x, Some(100.0), "declared pixel_size_x == 100µm");
    assert_eq!(geom.pixel_size_y, Some(100.0), "declared pixel_size_y == 100µm");
    assert_eq!(geom.max_dimension_x, Some(300), "declared max_dimension_x == 300µm");
    assert_eq!(geom.max_dimension_y, Some(300), "declared max_dimension_y == 300µm");

    // ---- STEP 2: convert the fixture through the public convert_with seam ----
    let dir = tempdir("geof01");
    let out_mzpeak = dir.join("declared.mzpeak");

    let reader = ImagingReader::open(fixture).expect("ImagingReader::open Synthetic_DeclaredGrid");
    let image_paths: [PathBuf; 0] = [];
    let outcome = convert_with(
        reader,
        &out_mzpeak,
        &image_paths,
        &EncodingOptions::legacy(),
        Some(&geom),
        Some(fixture),
    )
    .expect("convert_with declared-grid fixture must succeed");

    // The declared grid is CONSISTENT with the observed 3×3 coords — no inconsistency flag.
    assert!(
        !outcome.declared_geometry_inconsistent,
        "consistent declared grid must NOT set declared_geometry_inconsistent"
    );

    // ---- STEP 3: re-open archive and assert pixel_count_source == "declared" ----
    let mzreader = MzPeakReader::new(&out_mzpeak)
        .expect("MzPeakReader must open the produced declared-grid archive");

    // (a) metadata.imaging block — pixel_count_source == "declared"
    let imaging_val = mzreader
        .file_index()
        .metadata
        .get("imaging")
        .cloned()
        .expect("metadata.imaging must be present in the produced archive");

    assert_eq!(
        imaging_val.get("pixel_count_source").and_then(Value::as_str),
        Some("declared"),
        "declared-grid conversion must emit pixel_count_source == \"declared\"; got: {imaging_val:?}"
    );

    // (b) pixel_count must be {x:3, y:3}
    let pc = imaging_val
        .get("pixel_count")
        .expect("metadata.imaging.pixel_count must be present for a declared-grid fixture");
    assert_eq!(
        pc.get("x").and_then(Value::as_i64),
        Some(3),
        "pixel_count.x == 3 (declared grid)"
    );
    assert_eq!(
        pc.get("y").and_then(Value::as_i64),
        Some(3),
        "pixel_count.y == 3 (declared grid)"
    );

    // (c) absolute_offset_um: our fixture does NOT declare offsets; field must be absent (None).
    // (This exercises the "absent terms omitted, never fabricated" rule.)
    assert!(
        imaging_val.get("absolute_offset_um").is_none(),
        "absolute_offset_um must be absent when fixture declares no offsets (no fabrication)"
    );

    // (d) scan_settings_list — must be present, non-empty, and carry IMS:1000042/43
    let ssl = mzreader
        .file_index()
        .metadata
        .get("scan_settings_list")
        .cloned()
        .expect("metadata.scan_settings_list must be present (convert_with(Some(&geom)) emits it)");
    let entries = ssl.as_array().expect("scan_settings_list must be a JSON array");
    assert!(
        !entries.is_empty(),
        "scan_settings_list must have at least one entry"
    );
    let first = &entries[0];
    let params = first
        .get("parameters")
        .and_then(Value::as_array)
        .expect("scan_settings entry must have a parameters array");

    // IMS:1000042 and IMS:1000043 must be present in the facet (the declared grid counts).
    let has_1000042 = params.iter().any(|p| {
        p.get("accession").and_then(Value::as_str) == Some("IMS:1000042")
    });
    let has_1000043 = params.iter().any(|p| {
        p.get("accession").and_then(Value::as_str) == Some("IMS:1000043")
    });
    assert!(
        has_1000042,
        "scan_settings_list must carry IMS:1000042 (grid x count = 3); params: {params:?}"
    );
    assert!(
        has_1000043,
        "scan_settings_list must carry IMS:1000043 (grid y count = 3); params: {params:?}"
    );

    // Verify the values are "3" in the facet.
    let grid_x_val = params
        .iter()
        .find(|p| p.get("accession").and_then(Value::as_str) == Some("IMS:1000042"))
        .and_then(|p| p.get("value").and_then(Value::as_str))
        .expect("IMS:1000042 must carry a value");
    assert_eq!(grid_x_val, "3", "scan_settings_list IMS:1000042 value == \"3\"");

    // ---- STEP 4: reverse-convert the archive ----
    let rev_imzml = dir.join("declared_rev.imzML");
    let rev_ibd = dir.join("declared_rev.ibd");
    reverse_convert(&rev_imzml, &rev_ibd, &out_mzpeak)
        .expect("reverse::convert on declared-grid archive must succeed");
    assert!(rev_imzml.exists(), "reverse-emitted .imzML must exist");
    assert!(rev_ibd.exists(), "reverse-emitted .ibd must exist");

    // ---- STEP 5: forward↔reverse declared-geometry symmetry assertion ----
    let symmetry = assert_declared_geometry_symmetry(&geom, &rev_imzml)
        .expect("geometry symmetry assertion must not fail to parse the reverse imzML");
    assert!(
        symmetry.passed(),
        "declared geometry must survive forward→reverse: mismatches = {:?}",
        symmetry.mismatches
    );

    // Cleanup.
    std::fs::remove_dir_all(&dir).ok();
}

/// FIX-3 regression: when the declared grid is INCONSISTENT with observed coords (observed extent
/// exceeds the declared grid → GEOF-01 guard sets `pixel_count_source == "observed_max"`), the
/// reverse `.imzML` must NOT re-declare the OBSERVED extents as DECLARED IMS:1000042/43 max-count
/// geometry. Re-declaring observed extents as a declared grid would fabricate a declaration the
/// source never made and defeat the Phase-25 guard.
#[test]
fn observed_max_reverse_omits_declared_pixel_counts() {
    let fixture = Path::new(INCONSISTENT_FIXTURE);
    assert!(
        fixture.exists(),
        "inconsistent-grid fixture must be committed at {INCONSISTENT_FIXTURE}"
    );

    // Forward-convert. The declared 2×2 grid is inconsistent with the observed 3×3 coords.
    let geom = parse_scan_settings(fixture).expect("parse_scan_settings on inconsistent fixture");
    let dir = tempdir("fix3");
    let out_mzpeak = dir.join("inconsistent.mzpeak");
    let reader = ImagingReader::open(fixture).expect("ImagingReader::open inconsistent fixture");
    let image_paths: [PathBuf; 0] = [];
    let outcome = convert_with(
        reader,
        &out_mzpeak,
        &image_paths,
        &EncodingOptions::legacy(),
        Some(&geom),
        Some(fixture),
    )
    .expect("convert_with inconsistent-grid fixture must succeed");

    // The guard MUST have flagged the inconsistency (precondition for the FIX-3 path).
    assert!(
        outcome.declared_geometry_inconsistent,
        "observed coords exceed the declared grid → guard must flag declared_geometry_inconsistent"
    );

    // The archive's metadata.imaging must carry pixel_count_source == "observed_max" with the
    // observed 3×3 maxima (NOT the declared 2×2).
    let mzreader = MzPeakReader::new(&out_mzpeak).expect("MzPeakReader open inconsistent archive");
    let imaging_val = mzreader
        .file_index()
        .metadata
        .get("imaging")
        .cloned()
        .expect("metadata.imaging present");
    assert_eq!(
        imaging_val.get("pixel_count_source").and_then(Value::as_str),
        Some("observed_max"),
        "inconsistent grid must record pixel_count_source == observed_max; got {imaging_val:?}"
    );

    // Reverse-convert and inspect the emitted imzML header.
    let rev_imzml = dir.join("inconsistent_rev.imzML");
    let rev_ibd = dir.join("inconsistent_rev.ibd");
    reverse_convert(&rev_imzml, &rev_ibd, &out_mzpeak)
        .expect("reverse::convert on inconsistent archive must succeed");

    let text = std::fs::read_to_string(&rev_imzml)
        .or_else(|_| {
            // Header is Latin-1; read as bytes and lossily decode for the assertion.
            std::fs::read(&rev_imzml).map(|b| String::from_utf8_lossy(&b).into_owned())
        })
        .expect("read reverse imzML");

    assert!(
        !text.contains("IMS:1000042"),
        "observed_max reverse imzML must NOT carry IMS:1000042 (declared max-count) — FIX-3"
    );
    assert!(
        !text.contains("IMS:1000043"),
        "observed_max reverse imzML must NOT carry IMS:1000043 (declared max-count) — FIX-3"
    );

    std::fs::remove_dir_all(&dir).ok();
}
