#!/usr/bin/env python3
"""Generate docs/data-manifest.tsv — a committed inventory of data/** so the (gitignored,
~300 GB) corpus can be recovered if local data is deleted. For each file: relative path, size,
whether it is mirrored on s3://v09, and how to recover it. Recovery itself is scripts/restore-data.sh.

Usage:  python3 scripts/gen-data-manifest.py
Requires: aws CLI configured for the StackIT 'stackit' profile (to list the bucket)."""
import os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")
OUT  = os.path.join(ROOT, "docs", "data-manifest.tsv")
EP   = "https://object.storage.eu01.onstackit.cloud"

# recovery source per top-level data/ subdir (used when a file is NOT on S3)
RECOVER = {
    "imzml-examples":   "scripts/fetch-imzml-examples.sh",
    "mzML-examples":    "scripts/fetch-mzml-examples.sh  (PXD049028 entry: PRIDE raw + TRFP, see restore-data.sh)",
    "sdrf-examples":    "scripts/fetch-sdrf-examples.sh",
    "pwiz-examples":    "pwiz reference examples (mzpeak_prototyping) / publish-corpus.sh",
    "raw-bench":        "scripts/raw-bench-pipeline.sh  (regenerable benchmark scratch)",
    "raw-examples":     "scripts/raw-bench-pipeline.sh / original vendor RAW download (regenerable scratch)",
    "raw-replacements": "scripts/thermo-replacements-bench.sh  (regenerable benchmark scratch)",
    "demo":             "viewer demo asset",
    "validator_logs":   "transient — regenerated by the mzPeakValidator sweep",
}

def s3_keys():
    out = subprocess.run(
        ["aws", "--profile", "stackit", "--endpoint-url", EP, "s3", "ls", "s3://v09", "--recursive"],
        capture_output=True, text=True)
    keys = set()
    for line in out.stdout.splitlines():
        parts = line.split(None, 3)
        if len(parts) == 4:
            keys.add(parts[3])
    return keys

def main():
    if not os.path.isdir(DATA):
        sys.exit("no data/ directory")
    keys = s3_keys()
    rows, n_files, n_bytes, n_s3, n_s3_bytes = [], 0, 0, 0, 0
    for dirpath, _, files in os.walk(DATA):
        for fn in files:
            full = os.path.join(dirpath, fn)
            rel  = os.path.relpath(full, ROOT)          # e.g. data/mzML-examples/.../x.mzpeak
            try: size = os.path.getsize(full)
            except OSError: continue
            key  = os.path.relpath(full, DATA)          # S3 key = path minus data/
            top  = key.split(os.sep, 1)[0]
            on_s3 = key in keys
            recover = "aws s3 sync s3://v09 data/" if on_s3 else RECOVER.get(top, "(no recorded source — investigate)")
            rows.append((rel, size, "Y" if on_s3 else "N", recover))
            n_files += 1; n_bytes += size
            if on_s3: n_s3 += 1; n_s3_bytes += size
    rows.sort()
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("# data/** recovery manifest — regenerate with scripts/gen-data-manifest.py; recover with scripts/restore-data.sh\n")
        f.write(f"# {n_files} files, {n_bytes/1e9:.1f} GB total; {n_s3} on S3 ({n_s3_bytes/1e9:.1f} GB), "
                f"{n_files-n_s3} not on S3 ({(n_bytes-n_s3_bytes)/1e9:.1f} GB, recover via the listed script)\n")
        f.write("path\tbytes\ton_s3\trecover_via\n")
        for rel, size, s3, rec in rows:
            f.write(f"{rel}\t{size}\t{s3}\t{rec}\n")
    print(f"wrote {OUT}: {n_files} files, {n_bytes/1e9:.1f} GB; on-S3 {n_s3} ({n_s3_bytes/1e9:.1f} GB), "
          f"off-S3 {n_files-n_s3} ({(n_bytes-n_s3_bytes)/1e9:.1f} GB)")

if __name__ == "__main__":
    main()
